# development:
#   adapter: async
#
# test:
#   adapter: async
#
# production:
#   adapter: redis
#   url: redis://localhost:6379/1
#   channel_prefix: project-3_production

production: &production
  adapter: redis
  url: redis://h:p8430c2e9b115effd08a95b76eeaf43231cdc3fe07cb417686174179fe980fdb6@ec2-34-231-155-48.compute-1.amazonaws.com:41489
development: &development
  adapter: redis
  url: redis://h:p8430c2e9b115effd08a95b76eeaf43231cdc3fe07cb417686174179fe980fdb6@ec2-34-231-155-48.compute-1.amazonaws.com:41489
test: *development
