# development:
#   adapter: async
#
# test:
#   adapter: async
#
# production:
#   adapter: redis
#   url: redis://localhost:6379/1
#   channel_prefix: project-3_production

production: &production
  adapter: redis
  url: redis://stormy-dawn-37243.herokuapp.com:6379
development: &development
  adapter: redis
  url: redis://localhost:6379
test: *development
